EE_DVP = dvp-as
VCL = vcl

RENDERERS = \
	vertex_color_renderer \
	vertex_color_texture_renderer \
	project \
	project_clip \
	vertex_color \
	xgkick \
	jump_table

VSM_OBJS = $(addsuffix .vo, $(addprefix vu1/, $(RENDERERS)))
EE_OBJS += $(VSM_OBJS)
VSM_SOURCES = $(addsuffix _vcl.vsm, $(addprefix vu1/, $(RENDERERS)))

vu_progs: $(VSM_OBJS)

%.vo: %.vsm
	$(EE_DVP) $< -o $@

.PRECIOUS: %.vsm %.vcl_pp
%.vsm: %.vcl_pp
	$(VCL) $< > $@

%.vcl_pp: %.vcl
	cpp -P -undef $< > $@