EE_DVP = dvp-as
VCL = vcl

RENDERERS = \
	vertex_color_renderer

EE_OBJS += $(addsuffix .vo, $(addprefix vu1/, $(RENDERERS)))
VSM_SOURCES = $(addsuffix _vcl.vsm, $(addprefix vu1/, $(RENDERERS)))

%.vo: %.vsm
	$(EE_DVP) $< -o $@

%.vsm: %.vcl
	$(VCL)  $< >> $@