name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Get dependencies
      run: |
        apk add build-base binutils-dev git cmake xorriso assimp-dev musl-obstack-dev jsoncpp-dev

    - name: Compile ps2 engine
      run: |
        ./compile.sh

    - uses: actions/upload-artifact@v3
      with:
        name: test.iso
        path: build/test.iso
