name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk

    steps:
    - uses: actions/checkout@v3
    - name: Get dependencies
      run: |
        apk add build-base git cmake xorriso cxxopts-dev
        
    - name: Install ps2stuff
      run: |
        git clone https://github.com/ps2dev/ps2stuff.git dependencies/ps2stuff
        cd dependencies/ps2stuff && make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Install ps2gl
      run: |
        git clone https://github.com/ps2dev/ps2gl.git dependencies/ps2gl
        cd dependencies/ps2gl && make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Install meshoptimizer
      run: |
        git clone https://github.com/zeux/meshoptimizer.git dependencies/meshoptimizer
        cd dependencies/meshoptimizer
        mkdir -p build
        cd build
        cmake ..
        make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Compile egg-library
      run: |
        cd dependencies/egg-library
        make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Compile ps2-mesh-converter
      run: |
        cd tools/ps2-mesh-converter
        mkdir -p build
        cd build
        cmake ..
        make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Compile ps2 engine
      run: |
        make clean iso -j$(getconf _NPROCESSORS_ONLN)
