name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk

    steps:
    - uses: actions/checkout@v3
    - name: Get dependencies
      run: |
        apk add build-base binutils-dev git cmake xorriso assimp-dev musl-obstack-dev

    - name: Install openvcl/MASP
      run: |
        git clone https://github.com/nicholas477/openvcl.git dependencies/openvcl
        cd dependencies/openvcl/contrib/masp
        chmod +x ./configure && ./configure LIBS="-lobstack"
        make clean install -j$(getconf _NPROCESSORS_ONLN)
        cd ../../
        make clean install -j$(getconf _NPROCESSORS_ONLN)

        
    - name: Install ps2stuff
      run: |
        git clone https://github.com/ps2dev/ps2stuff.git dependencies/ps2stuff
        cd dependencies/ps2stuff && make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Install ps2gl
      run: |
        git clone https://github.com/nicholas477/ps2gl.git dependencies/ps2gl
        cd dependencies/ps2gl && make clean all install -j$(getconf _NPROCESSORS_ONLN) DEBUG=1
        cd glut && make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Install meshoptimizer
      run: |
        git clone https://github.com/zeux/meshoptimizer.git dependencies/meshoptimizer
        cd dependencies/meshoptimizer
        mkdir -p build
        cd build
        cmake ..
        make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Install cxxopts
      run: |
        git clone https://github.com/artpaul/cxxopts.git dependencies/cxxopts
        cd dependencies/cxxopts
        mkdir -p build
        cd build
        cmake ..
        make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Compile egg-library
      run: |
        cd dependencies/egg-library
        make clean all install -j$(getconf _NPROCESSORS_ONLN)
        mkdir build
        cd build
        cmake ..
        make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Compile ps2-mesh-converter
      run: |
        cd tools/ps2-mesh-converter
        mkdir -p build
        cd build
        cmake ..
        make clean all install -j$(getconf _NPROCESSORS_ONLN)
        
    - name: Compile ps2-manifest-generator
      run: |
        cd tools/ps2-manifest-generator
        mkdir -p build
        cd build
        cmake ..
        make clean all install -j$(getconf _NPROCESSORS_ONLN)

    - name: Compile ps2 engine
      run: |
        make clean iso -j$(getconf _NPROCESSORS_ONLN)

    - uses: actions/upload-artifact@v3
      with:
        name: game-iso
        path: build/test.iso
